# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/simpleUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(658, 692)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon2/icon2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gwScreen = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gwScreen.sizePolicy().hasHeightForWidth())
        self.gwScreen.setSizePolicy(sizePolicy)
        self.gwScreen.setMinimumSize(QtCore.QSize(640, 480))
        self.gwScreen.setMaximumSize(QtCore.QSize(640, 480))
        self.gwScreen.setInteractive(True)
        self.gwScreen.setObjectName("gwScreen")
        self.verticalLayout_2.addWidget(self.gwScreen)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.updateValue = QtWidgets.QSpinBox(self.groupBox_2)
        self.updateValue.setMinimum(50)
        self.updateValue.setMaximum(9999)
        self.updateValue.setProperty("value", 1000)
        self.updateValue.setObjectName("updateValue")
        self.horizontalLayout_2.addWidget(self.updateValue)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 658, 25))
        self.menubar.setObjectName("menubar")
        self.menuAction = QtWidgets.QMenu(self.menubar)
        self.menuAction.setObjectName("menuAction")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuAction.addAction(self.actionAbout)
        self.menuAction.addSeparator()
        self.menuAction.addAction(self.actionExit)
        self.menubar.addAction(self.menuAction.menuAction())

        self.retranslateUi(MainWindow)
        self.menubar.triggered['QAction*'].connect(MainWindow.processAction)
        self.pushButton.clicked.connect(MainWindow.loadDataFromDso)
        self.pushButton_2.clicked.connect(MainWindow.loadScreenFromDso)
        self.pushButton_3.clicked.connect(MainWindow.saveProgramScreen)
        self.checkBox.toggled['bool'].connect(MainWindow.setAutoUpdate)
        self.checkBox.clicked['bool'].connect(self.updateValue.setEnabled)
        self.pushButton_2.clicked['bool'].connect(self.checkBox.setChecked)
        self.pushButton_4.clicked.connect(MainWindow.saveDataToCSV)
        self.checkBox.clicked['bool'].connect(MainWindow.loadDataFromDso)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DSO screenshoter"))
        self.groupBox.setTitle(_translate("MainWindow", "Actions"))
        self.pushButton.setToolTip(_translate("MainWindow", "Loads data from DSO and paint wave by yourselves"))
        self.pushButton.setText(_translate("MainWindow", "Load data from DSO"))
        self.pushButton_4.setText(_translate("MainWindow", "Save data to CSV"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "Load screen data from DSO and paint them to program view"))
        self.pushButton_2.setText(_translate("MainWindow", "Screenshot from DSO"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "Save programs view to file"))
        self.pushButton_3.setText(_translate("MainWindow", "Save program screen"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Settings"))
        self.checkBox.setText(_translate("MainWindow", "Auto load data from DSO"))
        self.updateValue.setSuffix(_translate("MainWindow", "ms"))
        self.menuAction.setTitle(_translate("MainWindow", "Action"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
import images_rc
